// Code generated by metricsgen. DO NOT EDIT.

package p2p

import (
	"github.com/go-kit/kit/metrics/discard"
	prometheus "github.com/go-kit/kit/metrics/prometheus"
	stdprometheus "github.com/prometheus/client_golang/prometheus"
)

func PrometheusMetrics(namespace string, labelsAndValues ...string) *Metrics {
	labels := []string{}
	values := []string{}
	for i := 0; i < len(labelsAndValues); i += 2 {
		labels = append(labels, labelsAndValues[i])
		if i+1 < len(labelsAndValues) {
			values = append(values, labelsAndValues[i+1])
		}
	}
	withLabels := func(names ...string) []string {
		return append(append([]string{}, labels...), names...)
	}
	peerReceiveBytesVec := stdprometheus.NewCounterVec(stdprometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: MetricsSubsystem,
		Name:      "peer_receive_bytes_total",
		Help:      "Number of bytes received from a given peer.",
	}, withLabels("peer_id", "chID"))
	stdprometheus.MustRegister(peerReceiveBytesVec)
	peerSendBytesVec := stdprometheus.NewCounterVec(stdprometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: MetricsSubsystem,
		Name:      "peer_send_bytes_total",
		Help:      "Number of bytes sent to a given peer.",
	}, withLabels("peer_id", "chID"))
	stdprometheus.MustRegister(peerSendBytesVec)
	messageReceiveBytesVec := stdprometheus.NewCounterVec(stdprometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: MetricsSubsystem,
		Name:      "message_receive_bytes_total",
		Help:      "Number of bytes of each message type received.",
	}, withLabels("message_type"))
	stdprometheus.MustRegister(messageReceiveBytesVec)
	messageSendBytesVec := stdprometheus.NewCounterVec(stdprometheus.CounterOpts{
		Namespace: namespace,
		Subsystem: MetricsSubsystem,
		Name:      "message_send_bytes_total",
		Help:      "Number of bytes of each message type sent.",
	}, withLabels("message_type"))
	stdprometheus.MustRegister(messageSendBytesVec)
	return &Metrics{
		peerReceiveBytesVec:    peerReceiveBytesVec,
		peerSendBytesVec:       peerSendBytesVec,
		messageReceiveBytesVec: messageReceiveBytesVec,
		messageSendBytesVec:    messageSendBytesVec,
		globalLabelValues:      values,
		Peers: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "peers",
			Help:      "Number of peers.",
		}, labels).With(labelsAndValues...),
		PeerReceiveBytesTotal: prometheus.NewCounter(peerReceiveBytesVec).With(labelsAndValues...),
		PeerSendBytesTotal:    prometheus.NewCounter(peerSendBytesVec).With(labelsAndValues...),
		PeerPendingSendBytes: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "peer_pending_send_bytes",
			Help:      "Pending bytes to be sent to a given peer.",
		}, append(labels, "peer_id")).With(labelsAndValues...),
		NumTxs: prometheus.NewGaugeFrom(stdprometheus.GaugeOpts{
			Namespace: namespace,
			Subsystem: MetricsSubsystem,
			Name:      "num_txs",
			Help:      "Number of transactions submitted by each peer.",
		}, append(labels, "peer_id")).With(labelsAndValues...),
		MessageReceiveBytesTotal: prometheus.NewCounter(messageReceiveBytesVec).With(labelsAndValues...),
		MessageSendBytesTotal:    prometheus.NewCounter(messageSendBytesVec).With(labelsAndValues...),
	}
}

func NopMetrics() *Metrics {
	return &Metrics{
		Peers:                    discard.NewGauge(),
		PeerReceiveBytesTotal:    discard.NewCounter(),
		PeerSendBytesTotal:       discard.NewCounter(),
		PeerPendingSendBytes:     discard.NewGauge(),
		NumTxs:                   discard.NewGauge(),
		MessageReceiveBytesTotal: discard.NewCounter(),
		MessageSendBytesTotal:    discard.NewCounter(),
	}
}
